run:
  timeout: 2m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - unused
    - structcheck

  disable:
    - gocyclo
    - dupl
    - lll
    - funlen
    - nakedret
    - godot
    - golint

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

gofmt:
  simplify: true

linters-settings:
  goimports:
    local-prefixes: github.com/your/module
